services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=estudiantesdb
      - POSTGRES_USER=estudianteuser
      - POSTGRES_PASSWORD=estudiantepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: estudiantes-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/estudiantesdb
      - SPRING_DATASOURCE_USERNAME=estudianteuser
      - SPRING_DATASOURCE_PASSWORD=estudiantepass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  postgres_data:
